version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: vue-docker-image
    container_name: nuxt-docker
    ports:
      - 4000:3000
    volumes:
      - .:/app
      - /app/node_modules
